---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: worker-staging
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: worker
    namespace: instavote
  interval: 1h
  dependsOn:
  - name: redis-staging
  path: ./deploy/worker/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: instavote
  targetNamespace: instavote
  timeout: 2m0s
  validation: client

